# Adaptive PDE discretizations on cartesian grids : Algorithmic tools

## Part : Automatic differentiation
## Chapter : Reverse automatic differentiation

This notebook illustrates *reverse first order* automatic differentiation. Recall that this approach is recommended for functions from a large dimensional space, to a small dimensional space, and whose jacobian does not have a sparse structure. It is typically appropriate for large scale optimization problems.

**Disclaimer.** First order reverse automatic differentiation is a classical feature, found in many packages better optimized and maintained than this one. If you only need this specific feature, then it could be wise to use another implementation.

In [1]:
import sys; sys.path.append("..") # Allow imports from parent directory
from Miscellaneous import TocTools; TocTools.displayTOC('Reverse','Algo')

[**Summary**](Summary.ipynb) of this series of notebooks. 

[**Main summary**](../Summary.ipynb), including the other volumes of this work. 


# Table of contents

  * [1. Generating variables and requesting an expression's derivatives](#1.-Generating-variables-and-requesting-an-expression's-derivatives)
    * [1.1 Gradient](#1.1-Gradient)
    * [1.2 Hessian operator](#1.2-Hessian-operator)
  * [2. Linear operators and their adjoints](#2.-Linear-operators-and-their-adjoints)
    * [2.1 Linear mapping](#2.1-Linear-mapping)
    * [2.2 Linear inversion](#2.2-Linear-inversion)
  * [3 Non-linear operators](#3-Non-linear-operators)
    * [3.2 Loops](#3.2-Loops)




**Acknowledgement.** The experiments presented in these notebooks are part of ongoing research, 
some of it with PhD student Guillaume Bonnet, in co-direction with Frederic Bonnans.

Copyright Jean-Marie Mirebeau, University Paris-Sud, CNRS, University Paris-Saclay


**Known bugs and incompatibilities.** Our implementation of automatic differentiation is based on subclassing the numpy array class. While simple and powerful, this approach suffers from a few pitfalls, described in the notebook linked below.

In [2]:
TocTools.MakeLink('ADBugs','Algo')

Notebook [ADBugs](./Notebooks_Algo/ADBugs.ipynb) , from volume Algo [Summary](./Notebooks_Algo/Summary.ipynb) 

## 0. Importing the required libraries

In [3]:
import numpy as np
import scipy.sparse; import scipy.sparse.linalg

In [4]:
import NumericalSchemes.AutomaticDifferentiation as ad
import NumericalSchemes.FiniteDifferences as fd

In [5]:
def LInfNorm(a): return np.max(np.abs(a))

## 1. Generating variables and requesting an expression's derivatives

Reverse automatic differentiation works by keeping a history of the computations. The sensitivity of the result w.r.t some components is obtained by propagating the sensitivities backward in the computation queue and using the operator adjoints.

Our implementation of the reverseAD is differs from the denseAD or sparseAD classes: here we do not define an data type overloading the arithmetic operators and the basic special functions. Instead, the reverseAD class is only meant to keep a history of user specified computations.

This section only shows how to generate variables, and request an expression's derivatives. See the next section for an actual use of automatic differentiation.
For a beginning, we create an empty history.
<!---Our implementation of reverse automatic differentiation is probably --->

### 1.1 Gradient

In [6]:
x0=np.linspace(0,np.pi,4)
gridScale=x0[1]-x0[0]
u0=np.sin(x0)
v0=np.cos(x0)

In [7]:
# Create an empty history
rev = ad.Reverse.empty()
# Create AD variables w.r.t which the gradient will be required
u1 = rev.identity(constant=u0)
v1 = rev.identity(constant=v0)

The generated AD variables are of sparse AD type.

In [8]:
print("u1:",u1)
print("v1:",v1)

u1: spAD(array([0.00000000e+00, 8.66025404e-01, 8.66025404e-01, 1.22464680e-16]), array([[1.],
       [1.],
       [1.],
       [1.]]), array([[0],
       [1],
       [2],
       [3]]))
v1: spAD(array([ 1. ,  0.5, -0.5, -1. ]), array([[1.],
       [1.],
       [1.],
       [1.]]), array([[4],
       [5],
       [6],
       [7]]))


If we make some computation using the variables registered in the reverseAD class, then we can request the gradient of the final expression.

In [9]:
result = (u1**2+v1**2).sum()

In [10]:
rev.gradient(result)

array([ 0.00000000e+00,  1.73205081e+00,  1.73205081e+00,  2.44929360e-16,
        2.00000000e+00,  1.00000000e+00, -1.00000000e+00, -2.00000000e+00])

If needed, this expression can be reshaped similar to the input variables.

In [11]:
u_grad,v_grad = rev.to_inputshapes(rev.gradient(result))

In [12]:
assert LInfNorm(v_grad-2*v0) < 1e-6

In [13]:
[(1,2)]==[]

False

### 1.2 Hessian operator

The hessian operator may be accessed as well, using the Reverse2 submodule. Note that the hessian matrix itself is never assembled, since in applications it would typically be dense and of large size.

In [14]:
# Create an empty history
rev = ad.Reverse2.empty()
# Create AD variables w.r.t which the gradient will be required
u1 = rev.identity(constant=u0)
v1 = rev.identity(constant=v0)
result = (u1**2+v1**2).sum()

In [15]:
grad = rev.gradient(result) # Gradient
hess = rev.hessian(result) # Hessian operator

In [16]:
grad

array([ 0.00000000e+00,  1.73205081e+00,  1.73205081e+00,  2.44929360e-16,
        2.00000000e+00,  1.00000000e+00, -1.00000000e+00, -2.00000000e+00])

In this specific example, the hessian operator is twice the identity.

In [17]:
hess(grad)

array([ 0.00000000e+00,  3.46410162e+00,  3.46410162e+00,  4.89858720e-16,
        4.00000000e+00,  2.00000000e+00, -2.00000000e+00, -4.00000000e+00])

### 1.3 Simplification of the AD information

Our implementation of reverse AD partly does rely on sparse AD, for the elementary operations.
However, sparseness is easily lost, as in the example below, which may result in complexity issues.

In [72]:
rev = ad.Reverse2.empty()
u1 = rev.identity(shape=(n,n))
u2 = (1.+u1+u1**2).sum(axis=0)
result = (u2**2).sum(axis=0)

grad,hess = rev.gradient(result),rev.hessian(result)

In [73]:
print("Result AD size : ",result.size_ad2)

Result AD size :  272


We can take advantage of reverse AD to reintroduce some sparsity. 

**Important.** 
Simplification based on reverse AD should not be confused with simplification based on sparse AD. The latter is *more costly* (involving sorting), and *less efficient* (it would have no effect in the situation above).

In [74]:
rev = ad.Reverse2.empty()
u1 = rev.identity(shape=(n,n))
u2 = (1.+u1+u1**2).sum(axis=0)
u2_simpl = rev.simplify(u2) # Intermediate simplification
result = (u2_simpl**2).sum(axis=0)

grad_simpl,hess_simpl = rev.gradient(result),rev.hessian(result)

In [80]:
print("Result AD size with intermediate simplification : ",result_simpl.size_ad2)

Result AD size with intermediate simplification :  4


The complex symbolic perturbations in $u_2$ are replaced in $\_u_2$ with placeholders, with negative indices.

In [75]:
_u2

spAD2(array([0., 0., 0., 0.]), array([[1.],
       [1.],
       [1.],
       [1.]]), array([[-1],
       [-2],
       [-3],
       [-4]]), array([], shape=(4, 0), dtype=float64), array([], shape=(4, 0), dtype=int64), array([], shape=(4, 0), dtype=int64))

The relative dependency of the old and new symbolic perturbations is registered, which allows computing derivatives.

In [79]:
assert LInfNorm(grad-grad_simpl) < 1e-13
dir_hessian = grad**2+1.
assert LInfNorm(hess(dir_hessian)-hess_simpl(dir_hessian)) < 1e-13

## 2. Linear operators and their adjoints

We illustrate Reverse automatic differentiation, in its intended use case involving operators operators whose jacobians are expected to be both high-dimensional and non-sparse. Note that linear operators often fit this desciption. For instance:
* A linear mapping, given in sparse form, but iterated many times.
* The inverse of a linear mapping, given in sparse form.
* The fast fourier transform, etc

### 2.1 Linear mapping

We first construct some sparse matrix, for the exposition, based on a transport scheme implemented using upwind finite differences.

In [18]:
def TransportScheme(u,h,speed,dt):
    return u+dt*speed*fd.DiffUpwind(u,(1,),h,padding=0.)

In order to construct the matrix, we evaluate the scheme on a sparse AD variable.

In [19]:
speed = 1.; T=1.5; nsteps=5; dt = T/nsteps;
transport_ad = TransportScheme(ad.Sparse.identity(u0.shape),gridScale,speed,dt)

In [20]:
transport_matrix = scipy.sparse.coo_matrix(transport_ad.triplets()).tocsr()

We can now use this matrix in the course of reverse AD computations, mixing both linear and non-linear steps.

In [21]:
rev = ad.Reverse.empty() # Create the reverse AD environnement
u1 = rev.identity(constant=u0) # Generate the variables.
v1 = rev.identity(constant=v0)
u2 = rev.apply_linear_mapping(transport_matrix,u1**2,niter=nsteps) #Implement the desired method
result_Reverse = (u2*v1).sum()

Due to the numerous iterations, the variable $u_2$ does not depend in a sparse manner on $u_1$.
In our implementation, the variable $u_2$ is of sparseAD type but features negative placeholder indices. 
Likewise for the final computation result.

In [22]:
u2

spAD(array([5.02050076e-01, 4.17158585e-01, 1.38706040e-01, 2.77367654e-33]), array([[1.],
       [1.],
       [1.],
       [1.]]), array([[-1],
       [-2],
       [-3],
       [-4]]))

In [23]:
result_Reverse

spAD(array(0.64127635), array([ 1.00000000e+00,  5.00000000e-01, -5.00000000e-01, -1.00000000e+00,
        5.02050076e-01,  4.17158585e-01,  1.38706040e-01,  2.77367654e-33]), array([-1, -2, -3, -4,  4,  5,  6,  7]))

The negative indices are newly introduced symbolic perturbations, whose depedence on the original ones is known thanks to the registered adjoint. This is exploited for computing the gradient of the result.

In [24]:
rev.gradient(result_Reverse)

array([ 0.00000000e+00,  8.03222547e-01,  6.77741743e-01, -2.49367755e-17,
        5.02050076e-01,  4.17158585e-01,  1.38706040e-01,  2.77367654e-33])

We can check the validity of this implementation using dense automatic differentiation, since this specific instance is small.

In [25]:
n=x0.size
u1 = ad.Dense2.identity(constant=u0,shift=(0,n))
v1 = ad.Dense2.identity(constant=v0,shift=(n,0))
u2 = ad.apply_linear_mapping(transport_matrix,u1**2,niter=nsteps)
result_Dense2 = (u2*v1).sum()

In [26]:
assert LInfNorm(rev.gradient(result_Reverse) - result_Dense2.coef1) < 1e-13

Second order reverse automatic differentiation is also implemented.

In [27]:
rev = ad.Reverse2.empty()
u1 = rev.identity(constant=u0)
v1 = rev.identity(constant=v0)
u2 = rev.apply_linear_mapping(transport_matrix,u1**2,niter=nsteps) 
result_Reverse2 = (u2*v1).sum()

In [28]:
assert LInfNorm(rev.gradient(result_Reverse2) - result_Dense2.coef1) < 1e-13

In [29]:
grad = rev.gradient(result_Reverse2)
hess = rev.hessian(result_Reverse2)

Note that the hessian is provided as an operator, that can be applied to arbitrary vectors. This is enough to run e.g. the conjugate gradient method.

In [31]:
hess

<function NumericalSchemes.AutomaticDifferentiation.Reverse2.reverseAD2.hessian.<locals>.hess_operator(dir_hessian, coef2_init=None, with_grad=False)>

In [32]:
dir_hessian = grad**2+1.
assert LInfNorm(hess(dir_hessian) - np.dot(result_Dense2.coef2,dir_hessian)) < 1e-13

### 2.2 Linear inversion

Linear inversion is almost always a non-local procedure, but with a simple and explicit adjoint. It is again a good fit for reverse AD. The procedure is almost identical, except for the choice of a linear solver.

In [93]:
rev = ad.Reverse2.empty()
u1 = rev.identity(constant=u0)
v1 = rev.identity(constant=v0)

# Choose a solver, and request the inversion.
solver = scipy.sparse.linalg.spsolve
u2 = rev.apply_linear_inverse(solver,transport_matrix,u1**2) 

result_Reverse2 = (u2*v1).sum()

grad = rev.gradient(result_Reverse2)
hess = rev.hessian(result_Reverse2)

Again, we control the results in this simple instance using dense AD.

In [94]:
n=x0.size
u1 = ad.Dense2.identity(constant=u0,shift=(0,n))
v1 = ad.Dense2.identity(constant=v0,shift=(n,0))
u2 = ad.apply_linear_inverse(solver,transport_matrix,u1**2)
result_Dense2 = (u2*v1).sum()

In [95]:
assert LInfNorm(grad - result_Dense2.coef1) < 1e-13
dir_hessian = grad**2+1.
assert LInfNorm(hess(dir_hessian) - np.dot(result_Dense2.coef2,dir_hessian)) < 1e-13

## 3. Non-linear operators

In the previous section, we have shown how to apply reverse AD to operators which are either:
- linear
- non-linear but local
- compositions of the above

We discuss here the general case of arbitrary non-linear operators. These techniques are typically needed in the context of non-linear evolution equations.

<!---
Since solving linear problems is a common operation, a factory method `ad.Reverse.linear_solution_with_adjoint` is provided to produce functions equivalent to `mysolve`. It is illustrated in a further subsection.

Two equivalent syntaxes are available to evaluate a function using reverse automatic differentiation:
* Using `rev.apply`, where rev is the reverseAD variable keeping the history of the computations.
* Using `ad.apply`, and specifying the `reverse_history = rev` optional argument. This latter approach has the advantage of being compatible with the `envelope` keyword for differentiating extrema.
--->

### 3.1 Defining an operator and its adjoint.

For the purposes of illustration, we define an operator which:
- has multiple inputs, each multi-dimensional.
- has a multi-dimensional output.
- is nonlocal (because of the inner loop involving a linear mapping).

In [139]:
def my_operator(u,v,co_output=None,co_output2=None):    
    # Generate an operator-like AD environnement
    rev,(u1,v1) = ad.Reverse.operator_like(inputs=(u,v),co_output=co_output,co_output2=co_output2)
    
    # Do some computations
    u2 = rev.apply_linear_mapping(transport_matrix,u1**2,niter=nsteps)
    result = u2*v1
    
    # Return the suitably converted output
    return rev.output(result)

The non-linear operator defined above can be applied to scalar variables, or dense AD variables. (The multiplication with the `transport_matrix` forbids the use of sparse AD variables.)

In [179]:
result_scalar = (my_operator(u0,u0*v0)*v0).sum()

In [198]:
n=x0.size
u1 = ad.Dense2.identity(constant=u0,shift=(0,n))
v1 = ad.Dense2.identity(constant=v0,shift=(n,0))

result_Dense2 = (my_operator(u1,u1*v1)*v1).sum()

It can also be used in a reverse AD context. (Note that this is *recursive* reverse AD.)

In [181]:
ad.reload_submodules()

In [182]:
rev = ad.Reverse.empty()
u1 = rev.identity(constant=u0)
v1 = rev.identity(constant=v0)

result_Reverse = (rev.apply(my_operator,u1,u1*v1)*v1).sum()

grad = rev.gradient(result_Reverse)

In [183]:
assert LInfNorm(grad - result_Dense2.coef1) < 1e-13

In [169]:
ad.reload_submodules()

In [199]:
rev = ad.Reverse2.empty()
u1 = rev.identity(constant=u0)
v1 = rev.identity(constant=v0)

result_Reverse2 = (rev.apply(my_operator,u1,u1*v1)*v1).sum()

grad = rev.gradient(result_Reverse2)
hess = rev.hessian(result_Reverse2)

In [200]:
assert LInfNorm(grad - result_Dense2.coef1) < 1e-13
dir_hessian = grad**2+1.
assert LInfNorm(hess(dir_hessian)-np.dot(result_Dense2.coef2,dir_hessian)) < 1e-13

AssertionError: 

In [203]:
hess(dir_hessian)-np.dot(result_Dense2.coef2,dir_hessian)

array([-5.02050076e-01, -3.92611613e-01, -1.03733795e-01,  5.55111512e-17,
        0.00000000e+00, -4.08421426e-01, -1.21856271e-01,  2.73691106e-48])

array([ 2.21348023e+00,  2.00813490e+00,  1.44435055e+00,  2.89858746e-01,
        1.25718789e+00,  2.12221511e+00, -1.97028695e-01, -1.66420592e-32])

In [193]:
# Previous implem
rev = ad.Reverse2.empty()
u1 = rev.identity(constant=u0)
v1 = rev.identity(constant=v0)

result_Reverse2 = ((rev.apply_linear_mapping(transport_matrix,u1**2,niter=nsteps)*(u1*v1))*v1).sum()

grad = rev.gradient(result_Reverse2)
hess = rev.hessian(result_Reverse2)

In [194]:
assert LInfNorm(grad - result_Dense2.coef1) < 1e-13
dir_hessian = grad**2+1.
assert LInfNorm(hess(dir_hessian)-np.dot(result_Dense2.coef2,dir_hessian)) < 1e-13

### 3.1.1 Some testing

In [222]:
def my_operator(u,co_output=None,co_output2=None):    
    # Generate an operator-like AD environnement
    rev,(u1,) = ad.Reverse.operator_like(inputs=(u,),co_output=co_output,co_output2=co_output2)
    
    result = u1
    
    return rev.output(result)

In [228]:
n=x0.size
u1 = ad.Dense2.identity(constant=u0,shift=(0,n))
v1 = ad.Dense2.identity(constant=v0,shift=(n,0))

result_Dense2 = (my_operator(u1)*v1).sum()

In [234]:
rev = ad.Reverse2.empty()
u1 = rev.identity(constant=u0)
v1 = rev.identity(constant=v0)

result_Reverse2 = (rev.apply(my_operator,u1)*v1).sum()

grad = rev.gradient(result_Reverse2)
hess = rev.hessian(result_Reverse2)

In [235]:
assert LInfNorm(grad - result_Dense2.coef1) < 1e-13
dir_hessian = grad**2+1. 

In [236]:
hess(dir_hessian)

array([0.  , 0.  , 0.  , 0.  , 2.  , 1.25, 1.25, 2.  ])

In [237]:
np.dot(result_Dense2.coef2,dir_hessian)

array([1.  , 1.75, 1.75, 1.  , 2.  , 1.25, 1.25, 2.  ])

### 3.2 Loops

**Note on complexity** Reverse automatic differentiation requires saving program state at each intermediate computation steps.
If a program contains a loop, this may result in severe memory usage. Therefore, it is common to only store a small proportion of the intermediate states, referred to as keypoints, and to use recomputations for reconstructing the other steps. For best efficiency, this procedure must be made recursive. 


Using recursive reverse automatic differentiation, we can achieve this behavior.
*TODO : We will provide a helper function for that purpose.*

In [20]:
mysolve = ad.Reverse.linear_inverse_with_adjoint(scipy.sparse.linalg.spsolve,matrix)

In [21]:
rev = ad.Reverse.empty()
u1 = rev.identity(constant=u0)
v1 = rev.identity(constant=v0)

u3 = rev.iterate(mysolve,u1,niter=2)
#u3 = rev.apply_linear_inverse(matrix,scipy.sparse.linalg.spsolve,u1,niter=2) # Equivalent

result = (u3*v1).sum()

In [22]:
result

spAD(array(5.69821876), array([ 1.00000000e+00,  5.00000000e-01, -5.00000000e-01, -1.00000000e+00,
        4.74851563e+00,  2.84910938e+00,  9.49703126e-01,  1.34297549e-16]), array([-5, -6, -7, -8,  4,  5,  6,  7]))

In [23]:
rev.gradient(result)

array([1.09662271e+00, 2.74155678e+00, 3.83817949e+00, 3.83817949e+00,
       4.74851563e+00, 2.84910938e+00, 9.49703126e-01, 1.34297549e-16])