# Adaptive PDE discretizations on cartesian grids

## Part : Additional tools
## Chapter : Non rectangular domains

This notebook illustrates the implementation of monotone schemes on non-rectangular domains, with Dirichlet boundary conditions. We show how to describe the domain, and adapt the finite differences.

In [5]:
import sys; sys.path.append("../..") # Allow imports from parent directory
from Miscellaneous import TocTools; TocTools.displayTOC('Domains','NonDiv')

[**Summary**](Summary.ipynb) of this series of notebooks. 

[**Main summary**](../Summary.ipynb), including the other volumes of this work. 


# Table of contents




**Acknowledgement.** The experiments presented in these notebooks are part of ongoing research, 
some of it with PhD student Guillaume Bonnet, in co-direction with Frederic Bonnans.

Copyright Jean-Marie Mirebeau, University Paris-Sud, CNRS, University Paris-Saclay


In [17]:
from NumericalSchemes import Domain
from NumericalSchemes import AutomaticDifferentiation as ad

In [15]:
import scipy.linalg
import numpy as np

In [49]:
import importlib
Domain = importlib.reload(Domain)
ad.reload_submodules()

In [50]:
dom1 = Domain.Ball(np.array([0,0]))
dom2 = Domain.Box([[0,1],[0,1]])

In [52]:
dom2.level_is_distance

False

In [16]:
scipy.linalg.norm(np.array([1,1]))

1.4142135623730951

In [19]:
scipy.linalg.norm(ad.Dense.identity(constant=[1,1]))

1.4142135623730951

In [31]:
x= np.ones((2,2))
ad.Optimization.norm(x,axis=0,keepdims=True,averaged=True)

array([[1., 1.]])

In [32]:
np.array([[1,2],[3,4],[5,6]]).shape

(3, 2)

In [33]:
np.maximum(np.array([1,-1]),0.)

array([1., 0.])

In [59]:
np.minimum(*(np.array([1,2]),np.array([1,2]),np.array([0,3])))

array([1, 2])

In [56]:
np.minimum(np.array([1,2]),np.array([0,3]))

array([0, 2])

In [61]:
1 not in [1,2,3]

False

In [63]:
all(True,False,True)

TypeError: all() takes exactly one argument (3 given)

In [64]:
print("\\")

\
