Recursive AD

In [1]:
import sys; sys.path.append("../..") # Allow imports from parent directory

In [2]:
from NumericalSchemes import AutomaticDifferentiation as ad

In [3]:
import numpy as np
from matplotlib import pyplot as plt

In [36]:
def reload_packages():
    import importlib
    ad = importlib.reload(sys.modules['NumericalSchemes.AutomaticDifferentiation'])
    ad.misc = importlib.reload(ad.misc)
    ad.Sparse = importlib.reload(ad.Sparse)
    ad.Dense = importlib.reload(ad.Dense)
    ad.Sparse2 = importlib.reload(ad.Sparse2)
    ad.Dense2 = importlib.reload(ad.Dense2)

In [5]:
x = np.zeros((2,),object)

In [9]:
x[0]=ad.Dense.identity(constant=1)
x[1]=2*x[0]

In [14]:
X = ad.Dense.identity(constant=x)

In [17]:
X**2

denseAD(array([denseAD(array(1),array([2.])), denseAD(array(4),array([8.]))],
      dtype=object),
array([[denseAD(array(2.),array([2.])), denseAD(array(0.),array([0.]))],
       [denseAD(array(0.),array([0.])), denseAD(array(4.),array([4.]))]],
      dtype=object))

In [30]:
y = ad.Dense.identity(constant=[1.,2.])
z=np.zeros((2,),object)

In [31]:
for i,yi in enumerate(y): z[i]=yi

In [32]:
z

array([denseAD(array(1.),array([1., 0.])),
       denseAD(array(2.),array([0., 1.]))], dtype=object)

In [33]:
np.array([zi.coef for zi in z])

array([[1., 0.],
       [0., 1.]])

In [35]:
np.prod((1,2,3))

6

In [82]:
reload_packages()

In [85]:
#arr = ad.Dense.identity(constant=np.arange(8).reshape((2,2,2)),shape_free = ())
arr = np.arange(8).reshape((2,2,2))+ad.Dense.identity(constant=1)

In [86]:
arr

denseAD(array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]]),
array([[[[1.],
         [1.]],

        [[1.],
         [1.]]],


       [[[1.],
         [1.]],

        [[1.],
         [1.]]]]))

In [63]:
arr.shape

(2, 2, 2)

In [51]:
arr_diss = ad.disassociate(arr,shape_free = (2,2))

In [55]:
arr_ass = ad.associate(arr_diss)

In [56]:
arr_ass-arr

denseAD(array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]]),
array([[[[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]]]]))

In [54]:
arr_diss[0,0]

denseAD(array([0, 1]),
array([[1.],
       [1.]]))

In [70]:
test=np.array((2,2))
test=np.broadcast_to(test,(2,2))
test.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False